version: '3.8'

services:
  web:
    container_name: shop_django
    build:
      context: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7001:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=shop_api_db
      - HOST_DB=shop_api_db
      - POSTGRES_HOST=shop_api_db
    volumes:
      - .:/app
    depends_on:
      - shop_api_db
      - redis

  shop_api_db:
    image: postgres:14-alpine
    container_name: shop_postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME:-${NAME_DB:-magazin_db}}
      POSTGRES_USER: ${DB_USER:-${USER_DB:-magazin_db_user}}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-${PASSWORD_DB:-123}}
    ports:
      - "5433:5432"  # <-- Изменили внешний порт с 5432 на 5433
    env_file:
      - .env
    networks:
      default:
        aliases:
          - postgres
          - shop_api_db
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shop_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery_worker:
    container_name: shop_worker
    build:
      context: .
    command: python -m celery -A shop_api worker --loglevel=DEBUG
    depends_on:
      - redis
      - shop_api_db
    env_file:
      - .env
    environment:
      - DB_HOST=shop_api_db
      - HOST_DB=shop_api_db
      - POSTGRES_HOST=shop_api_db
    volumes:
      - .:/app

  celery_beat:
    container_name: shop_beat
    build:
      context: .
    command: python -m celery -A shop_api beat --loglevel=DEBUG
    depends_on:
      - redis
      - shop_api_db
    env_file:
      - .env
    environment:
      - DB_HOST=shop_api_db
      - HOST_DB=shop_api_db
      - POSTGRES_HOST=shop_api_db
    volumes:
      - .:/app

  celery_flower:
    container_name: shop_flower
    build:
      context: .
    command: python -m celery -A shop_api flower --port=5555
    ports:
      - "5556:5555"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  db-data:
  redis-data: